version: "3.7"
services:
 zookeeper:
   container_name: zookeeper
   image: confluentinc/cp-zookeeper:latest
   environment:
     ZOOKEEPER_SERVER_ID: 1
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000
   ports:
     - "2181:2181"
 kafka:
   container_name: kafka
   image: confluentinc/cp-kafka:latest
   ports:
     - "9092:9092"
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
   depends_on:
     - zookeeper
 kafdrop:
   container_name: kafdrop
   image: obsidiandynamics/kafdrop
   ports:
     - "9000:9000"
   environment:
     KAFKA_BROKERCONNECT: kafka:29092
   depends_on:
     - kafka
 mongodb:
   image: mongo
   container_name: mongo
   restart: always
   ports:
     - "27017:27017"
   environment:
     - MONGO_INITDB_DATABASE=userdb
   volumes:
     - ./awdadb/mongodb:/data/db
 mysqldb:
   container_name: mysql
   restart: always
   image: mysql
   ports:
     - "33061:3306"
   environment:
     MYSQL_DATABASE: awda
     MYSQL_ROOT_PASSWORD: awdadb
   volumes:
     - ./awdadb/mysql:/var/lib/mysql
 redis:
   image: redis
   container_name: redis
   ports:
     - "6379:6379"
   environment:
     - ALLOW_EMPTY_PASSWORD=yes
     - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
  restart: always
  container_name: elasticsearch
  environment:
    - discovery.type=single-node
    - cluster.name=cluster-user
  ports:
    - "9200:9200"
  networks:
    - elastic-network
  volumes:
    - es-data:/usr/share/elasticsearch/data
 rabbitmq:
   container_name: rabbitmq
   image: rabbitmq:management
   restart: no
   ports:
     - "5672:5672"
     - "15672:15672"
networks:
  elastic-network:
    driver: bridge
volumes:
  es-data:
    driver: local